name: Build WearOS APK
on: [push]

env:
  PROJECT_DIR: 'GWSensorDash'   # change to 'GW7SensorDash' if your Gradle files are in that subfolder

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout
        run: |
          echo "== repo root =="; ls -la
          echo "== project dir =="; ls -la "${PROJECT_DIR}"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Ensure Gradle wrapper exists (bootstraps 8.7 if missing)
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "No gradlew found, bootstrapping wrapper..."
            curl -L https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
            unzip -q gradle.zip
            ./gradle-8.7/bin/gradle wrapper --gradle-version 8.7
            chmod +x ./gradlew
          fi
          ./gradlew --version

      - name: Build debug APK (verbose; log to file)
        run: |
          set -o pipefail
          ./gradlew --no-daemon --stacktrace --info assembleDebug 2>&1 | tee gradle-build.log

      - name: Upload build log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: ${{ env.PROJECT_DIR }}/gradle-build.log

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: gw7-sensor-dash-debug-apk
          path: app/build/outputs/apk/debug/*.apk
